In [15]:
from utils import get_max_angle
import numpy as np
accel_dist = 0.1
min_pot = 513
max_pot = 635
center_pot = 594

In [19]:
dt = 0.001
input_str = \
'''
8293,-6988,21092,223
6338,-2560,19436,222
5201,-2100,18076,238
5753,-2248,17980,241
4887,-3624,18232,231
2869,-2188,17472,222
-767,-2224,17292,222
-5714,-48,18248,223
-9981,-3204,17212,220
-13637,-5092,16724,239
-12708,-1932,17548,225
-10120,180,23728,221
-9865,1092,25252,220
-11567,2700,27924,219
-12922,-456,24612,238
-11864,1184,26876,234
-9956,4508,27868,223
-9435,6184,27692,220
-9306,5200,27640,219
-7753,7056,28912,216
-5696,7492,29544,227
-3450,8912,28564,237
-1799,8384,29460,233
-564,8632,29468,223
1728,9996,31016,217
3595,7048,29472,215
3833,9024,27124,214
4557,10336,27476,214
5623,5424,31004,212
6848,3956,29556,222
8472,4324,26724,231
7971,5724,25940,234
7823,7984,24956,231
8220,508,28392,227
9628,5328,26708,219
10521,4636,25520,212
8860,6392,21940,212
6226,-1964,23736,212
5374,-3184,24420,211
4876,6236,22776,221
1875,4944,23188,227
822,5040,18736,230
734,-5672,19476,232
2545,-600,18468,222
3673,4480,17944,215
1920,3012,20388,210
812,952,20468,210
1463,2372,19988,211
644,2088,18732,211
-180,2464,18352,211
-522,1584,17692,211
372,1728,18360,211
29,-824,18512,210
-1025,-132,18488,216
-2208,3060,18176,229
-4082,852,17396,231
-4884,-812,18400,219
-5516,-468,20076,211
-5107,3044,20888,213
-5803,2292,23068,212
-6422,1832,21972,212
-6277,-4,21240,216
-6184,-572,22908,230
-6238,2800,23980,227
-6462,2096,24724,216
-6533,2228,24504,209
-7427,3528,26676,212
-8316,1600,25180,210
-6771,1848,25052,214
-6343,5200,27456,229
-6368,3052,29224,228
-5039,5348,26232,214
-3471,4948,26764,209
-879,6724,27304,209
1547,4436,28432,208
5412,5360,28060,209
8142,5424,27136,210
10090,4100,28184,223
10576,3740,26988,229
10109,4684,24096,219
9361,944,23528,216
7928,-2024,24752,209
7942,-768,23972,209
8690,136,23132,209
8125,-804,20380,209
8746,-1900,21772,209
8625,-5724,21448,221
8548,-2536,20024,228
5603,-2292,19892,220
3275,-2772,19208,210
2614,-1612,19264,207
-855,-4256,14336,208
-3600,1372,14804,206
-7094,-3820,19816,224
-7834,-1660,21436,222
-7166,-2312,19536,208
-6218,-2172,20596,208
-5462,-1232,21344,207
-6594,-1156,22684,224
-10040,584,23348,228
-12602,-2252,22308,208
-12325,-1232,23800,208
-10549,3376,26152,206
-9369,2376,26172,222
-7243,3916,27256,228
-6199,4816,28020,218
-4972,5924,28768,208
-3780,6224,28472,208
-2922,4996,29200,208
-1570,6168,28924,207
-86,7764,29012,210
2354,8892,28656,221
4482,8376,26700,226
5976,3740,27808,225
8104,3328,29004,218
10932,2800,27260,209
14037,3496,26320,206
15118,1988,25416,205
14596,-1012,25444,207
12530,924,23808,218
10299,1196,22696,224
6874,932,21716,226
3800,-2796,20292,212
2307,-2140,18984,204
1789,-2728,18428,206
2158,-1536,18992,205
2460,-3208,19056,205
2995,-856,18332,218
1530,-1100,20024,226
-1004,-1172,20096,214
-3566,-3396,20416,205
-5619,-2500,19968,205
-8843,-2368,22148,208
-12063,-1492,19760,226
-12498,132,21180,216
-11230,1400,22284,206
-9009,2136,24128,206
-7258,2548,25008,205
-6102,2684,26328,212
-5457,4084,27492,226
-3995,4984,27692,225
-3170,3376,27840,211
-2092,4436,27704,206
-1857,3804,28908,207
-1039,3184,27788,205
614,5448,27856,205
3159,2484,26916,209
6373,2804,26756,222
9750,3596,26920,225
10644,2400,26048,220
11249,3152,25044,209
11040,1604,23852,206
9149,-1332,24776,206
6395,-1236,23348,204
2969,-1880,21852,216
-407,-1972,22544,224
-2899,-1956,22492,216
-6241,-1212,23536,206
-9158,-1380,22624,206
-10383,-152,24028,206
-10015,900,24784,222
-9464,2468,26272,226
-8109,3648,25784,214
-6707,4360,26684,206
-4604,3860,26144,207
-2095,4668,27316,206
-228,3896,27380,206
845,4204,28236,206
147,3732,27816,209
129,4328,27724,214
868,4368,27556,217
2215,3628,26724,223
3772,3836,27072,224
6529,4276,27092,217
9072,3224,26680,208
9425,2236,27212,206
8844,816,27100,204
7012,1344,25624,205
5396,20,24264,205
4520,-376,24424,206
4824,-1604,24012,205
6097,-1104,23756,212
6734,-1024,22900,223
6086,-716,23216,225
4626,-1592,22248,212
3585,-2704,21752,205
3412,-1872,20944,205
2843,-1136,20912,206
2144,-1524,19872,208
1607,-884,19056,218
1475,-2580,19808,223
952,-1700,19844,220
40,-2140,19856,217
-223,-1584,19836,205
-233,-1840,19456,206
-409,-2444,19216,206
-762,-2532,19676,206
-1019,-2184,19524,222
-1265,-2296,20028,220
-2743,-1100,20996,205
-4087,-2320,19896,205
-4163,-2012,21200,205
-4434,-1992,21432,222
-3819,-668,22412,225
-3893,-112,23760,214
-6760,-200,23256,206
-7758,-1584,23344,206
-6583,356,23312,206
-4763,1528,23332,205
-1745,1792,23992,221
648,1484,25668,223
2045,1628,25500,225
3742,912,25260,223
4537,1084,25116,214
5224,-620,24556,208
5064,-344,24224,206
4556,-360,23336,205
3385,-628,22836,203
1921,-940,22400,205
988,-1836,21912,203
392,-1492,21680,210
384,-736,22340,215
127,-1044,22040,223
289,-1604,22604,223
241,-1628,22576,218
-223,-836,22944,210
-244,-1132,22128,204
-192,-636,22372,204
-482,-564,22032,203
-858,-868,22660,205
-1565,-880,21708,208
-1855,-1692,22180,223
-2280,-1052,22636,216
-2500,628,23596,208
-2675,-220,23468,204
-3160,244,23608,205
-4184,320,24572,203
-4938,-508,24516,203
-3446,44,23780,205
-1248,884,23940,216
764,1456,24180,222
2701,1424,24360,223
4595,824,24300,224
6070,1164,23852,217
5531,948,24488,214
4915,-516,24336,208
3726,-196,23772,204
2642,-512,22792,203
1998,-1364,21844,203
1041,-1052,21208,204
971,-1172,22232,212
541,-1268,21108,220
629,-1204,21540,222
1360,-1032,21856,216
953,-1112,22120,208
646,-1628,22080,204
279,-1016,22156,203
-394,-1384,21424,204
-76,-1188,21524,204
-233,-1084,21460,209
-172,-1152,21352,222
-78,-1364,22140,224
85,-556,20784,225
500,-1024,21360,220
270,-872,21580,215
114,-1124,20944,208
62,-1172,21404,205
-151,-1248,21392,205
-27,-1280,21796,205
-112,-1168,21340,204
-287,-1036,21324,212

'''

In [20]:
observations = []
for line in input_str.split():
    vals = list(map(int, line.split(',')))
    assert len(vals) == 4
    w = vals[0] / 32768 * 500
    a1 = vals[1] / 32768 * 2
    a2 = vals[2] / 32768 * 2
    eps = (a1**2 + a2**2)**0.5 / accel_dist
    pot = max(min_pot, min(vals[3], max_pot))
    if pot > center_pot:
        alpha = (pot - center_pot) / (max_pot - center_pot) * get_max_angle()
    else:
        alpha = (center_pot - pot) / (center_pot - min_pot) * get_max_angle()
    observations.append(np.array([alpha, w, eps]))
     

In [39]:
from utils import signal_to_force
la = 0.5
mu = 0.5
num_rolling = 5
force_speed_reaction = signal_to_force(2000+10) - signal_to_force(2000)

n = len(observations)
actions = np.random.binomial(1, p=0.5, size=n)
filtered_observations = []

x = np.array([0., 0., 0.])

F = np.array([
    [1, dt, 0],
    [0, 1, dt],
    [0, 0, 1]
])

z_rolling = [0.] * num_rolling

for i in range(n):
    u_ = actions[i] * force_speed_reaction
    u = np.array([0., 0., u_]) 
    z = observations[i]
    z_av = mu * z + (1 - mu) * np.mean(np.array(z_rolling), axis=0)
    x = la * (F @ x + u) + (1 - la) * z_av
    z_rolling.append(z.copy())
    del z_rolling[0]
    filtered_observations.append(x.copy())


C:\Users\Danill\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:25: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


[array([ 0.06326819, 31.63528442,  3.41316124]),
 array([ 0.12337356, 46.32395695,  5.39871795]),
 array([ 0.17342422, 54.16748545,  6.75243559]),
 array([ 0.21502495, 64.16368755,  7.9955411 ]),
 array([ 0.25347705, 70.24807299,  9.21884965]),
 array([ 0.28839893, 69.32130339, 10.27095629]),
 array([ 0.30539649, 50.85002179, 10.62973753]),
 array([ 0.30465963, 17.3225682 , 10.84433235]),
 array([  0.28752747, -24.04584867,  10.8401957 ]),
 array([  0.25827718, -70.68068173,  10.83826524]),
 array([   0.22033462, -104.58693589,   10.82977592]),
 array([   0.18441021, -123.55193856,   11.75383964]),
 array([   0.15696551, -139.19700276,   12.64399765]),
 array([ 1.35420623e-01, -1.56678666e+02,  1.37275252e+01]),
 array([ 1.15907349e-01, -1.71797893e+02,  1.40665464e+01]),
 array([ 9.85910990e-02, -1.74775885e+02,  1.47798280e+01]),
 array([ 8.84439776e-02, -1.68342162e+02,  1.56441022e+01]),
 array([ 8.65872787e-02, -1.63012288e+02,  1.62355628e+01]),
 array([ 8.83238660e-02, -1.595268